services:
  mongo:
    image: mongo:8.2.5
    container_name: mongodb
    platform: linux/amd64
    ports:
      - "27007:27017"
    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    restart: always

  pgvector:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: pgvector
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - backend
    restart: always


networks:
  backend:

volumes:
  mongodata:
  pgdata: