APP_NAME = "mini-RAG"
APP_VERSION = "0.1"
OPEN_API_KEY= ""

FILE_ALLOWED_TYPES = ["text/plain", "application/pdf"]
FILE_MAX_SIZE = 1 # MB
FILE_DEFAULT_CHUNK_SIZE = 512000 # 512KB

# DATABASE — for docker compose use host pgvector and the same password as docker/env/.env.Postgres
POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="postgres_password"
POSTGRES_HOST="pgvector"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="minirag"


# LLM CONFIG 
GENERATION_BACKEND = "OPENAI"
EMBEDDING_BACKEND = "HUGGINGFACE"

OPENAI_API_URL= "https://openrouter.ai/api/v1"

OPENAI_API_KEY= ""
COHERE_API_KEY= ""
HF_API_KEY= ""

GENERATION_MODEL_ID= "stepfun/step-3.5-flash:free"
EMBEDDING_MODEL_ID= "BAAI/bge-m3"
EMBEDDING_MODEL_SIZE=1024


INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=2000
GENERATION_DEFAULT_TEMPERATURE=0.1

# VectorDB CONFIG
VECTOR_DB_BACKEND_LITERAL = ["QDRANT","PGVECTOR"]
VECTOR_DB_BACKEND = "PGVECTOR"
VECTOR_DB_PATH= "qdrant_db"
VECTOR_DB_DISTANCE_METHOD= "cosine"
VECTOR_DB_PGVEC_INDEX_THRESHOLD = 100


# Template Configs
PRIMARY_LANG = "en"
DEFAULT_LANG = "en"

# 
WINDOWS_RESERVED = ["CON","PRN","AUX","NUL","COM1","COM2","COM3","COM4","COM5","COM6","COM7","COM8","COM9","LPT1","LPT2","LPT3","LPT4","LPT5","LPT6","LPT7","LPT8","LPT9"]